### PR TITLE
language improvement

### PR DESCRIPTION
**Pull request by Onefivefournine**
Removed lang declarations to separate files, also it now declares only needed language

### CODE REVIEW

**Comment by Mi-Al** [comment]
Hello! Thank you for your commit, I appreciate it and I like the idea to separate language files.
There are some issues with it:

- some strings are broken: \033 (and others) replaced with squares
- we should not contain blacklist.txt and cracked.txt files in the repository to protect user custom files from overwriting

It will be cool if you can fix these issues.

In addition, one more my issue: I cannot test the script right now because my hardware is out of order. I will continue to develop the script some weeks or months later. That time I will accept the commit. I will create ‘Contribution’ section to remind you and every participant.

**Comment by Onefivefournine** [comment]
Yeah, I see the issue with strings, trying to fix it now...
I just added blacklist.txt and cracked.txt to gitignore so that they would not be pushed to the repo.

**Comment by Onefivefournine** [comment]
Great! I have some more ideas for output improvement, let's hope I will get time to code them 😄

**Comment by Mi-Al** [comment]
I am adding the new features right now. ))) Wait for new release soon!

**Pull request merged**
